-- MySQL Script generated by MySQL Workbench
-- Thu Mar 21 14:50:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema db_mlm
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_mlm` ;

-- -----------------------------------------------------
-- Schema db_mlm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_mlm` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `db_mlm` ;

-- -----------------------------------------------------
-- Table `bankcodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bankcodes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bankcodes` (
  `bankcode` INT NOT NULL,
  `bankname` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`bankcode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `branchcodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `branchcodes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `branchcodes` (
  `bankcode` INT NOT NULL,
  `branchcode` INT NOT NULL,
  `branchname` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`bankcode`, `branchcode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `commission_payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `commission_payment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `commission_payment` (
  `idCommissionPayment` INT NOT NULL AUTO_INCREMENT,
  `Employees_idEmployees` INT NOT NULL,
  `Value` DOUBLE NULL DEFAULT NULL,
  `PaidDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idCommissionPayment`),
  CONSTRAINT `fk_CommissionPayment_Employees1`
    FOREIGN KEY (`Employees_idEmployees`)
    REFERENCES `employees` (`idEmployees`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;
CREATE INDEX `fk_CommissionPayment_Employees1_idx` ON `commission_payment` (`Employees_idEmployees` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `earning_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `earning_details` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `earning_details` (
  `idEarning` INT NOT NULL AUTO_INCREMENT,
  `Price` DOUBLE NULL DEFAULT NULL,
  `Value` DOUBLE NULL DEFAULT NULL,
  `IsDirectCommission` TINYINT NULL DEFAULT NULL,
  `Employee` VARCHAR(10) NULL DEFAULT NULL,
  `SalesOrders_idSalesOrders` INT NOT NULL,
  `SalesQty` DOUBLE NULL DEFAULT '0',
  `SalesValue` DOUBLE NULL DEFAULT '0',
  PRIMARY KEY (`idEarning`),
  CONSTRAINT `fk_EarningDetils_SalesOrders1`
    FOREIGN KEY (`SalesOrders_idSalesOrders`)
    REFERENCES `salesorders` (`sonumber`))
ENGINE = InnoDB
AUTO_INCREMENT = 621140
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;
CREATE INDEX `fk_EarningDetils_SalesOrders1_idx` ON `earning_details` (`SalesOrders_idSalesOrders` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `earningsummary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `earningsummary` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `earningsummary` (
  `EmpNumber` VARCHAR(45) NOT NULL,
  `Employees_idEmployees` INT NULL DEFAULT NULL,
  `TotalEarnings` DOUBLE NULL DEFAULT '0',
  `TotalPayed` DOUBLE NULL DEFAULT '0',
  `TotalDirectCommission` DOUBLE NULL DEFAULT '0',
  `TotalIndirectCommission` DOUBLE NULL DEFAULT '0',
  `LastPayementDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`EmpNumber`),
  CONSTRAINT `fk_EarningSummery_Employees1`
    FOREIGN KEY (`Employees_idEmployees`)
    REFERENCES `employees` (`idEmployees`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;
CREATE INDEX `fk_EarningSummery_Employees1_idx` ON `earningsummary` (`Employees_idEmployees` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employees` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `employees` (
  `idEmployees` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(100) NULL DEFAULT NULL,
  `LastName` VARCHAR(100) NULL DEFAULT NULL,
  `NIC` VARCHAR(15) NULL DEFAULT NULL,
  `EmpNumber` VARCHAR(10) NULL DEFAULT NULL,
  `Ref` VARCHAR(10) NULL DEFAULT NULL,
  `Phone` VARCHAR(15) NULL DEFAULT NULL,
  `HouseNumber` VARCHAR(50) NULL DEFAULT NULL,
  `Street` VARCHAR(100) NULL DEFAULT NULL,
  `City` VARCHAR(45) NULL DEFAULT NULL,
  `Province` VARCHAR(45) NULL DEFAULT NULL,
  `PostalCode` VARCHAR(45) NULL DEFAULT NULL,
  `AccountNum` VARCHAR(45) NULL DEFAULT NULL,
  `BankName` VARCHAR(45) NULL DEFAULT NULL,
  `BankCode` VARCHAR(45) NULL DEFAULT NULL,
  `BranchName` VARCHAR(45) NULL DEFAULT NULL,
  `BranchCode` VARCHAR(45) NULL DEFAULT NULL,
  `EmpStatus` TINYINT NULL DEFAULT '1',
  `JoinedDate` DATE NULL DEFAULT NULL,
  `Address` VARCHAR(155) NULL DEFAULT NULL,
  `PhoneAlt` VARCHAR(15) NULL DEFAULT NULL,
  `nameinbank` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idEmployees`))
ENGINE = InnoDB
AUTO_INCREMENT = 35567
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `itemsmaster`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `itemsmaster` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `itemsmaster` (
  `idItems` INT NOT NULL AUTO_INCREMENT,
  `ItemCode` VARCHAR(45) NULL DEFAULT NULL,
  `ItemName` VARCHAR(45) NULL DEFAULT NULL,
  `Commission` DOUBLE NULL DEFAULT NULL,
  `Price` DOUBLE NULL DEFAULT NULL,
  `ItemStatus` TINYINT NULL DEFAULT '1',
  `Level1` DOUBLE NULL DEFAULT '0',
  `Level2` DOUBLE NULL DEFAULT '0',
  `Level3` DOUBLE NULL DEFAULT '0',
  `Level4` DOUBLE NULL DEFAULT '0',
  PRIMARY KEY (`idItems`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;
CREATE UNIQUE INDEX `ItemCode_UNIQUE` ON `itemsmaster` (`ItemCode` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `saleslines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `saleslines` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `saleslines` (
  `linenumber` INT NOT NULL AUTO_INCREMENT,
  `ContactName` VARCHAR(45) NULL DEFAULT NULL,
  `ContactNo` VARCHAR(45) NULL DEFAULT NULL,
  `SalesDate` VARCHAR(45) NULL DEFAULT NULL,
  `DeliveryDate` VARCHAR(45) NULL DEFAULT NULL,
  `itemcode` VARCHAR(45) NULL DEFAULT NULL,
  `unitprice` DOUBLE NULL DEFAULT NULL,
  `commission` DOUBLE NULL DEFAULT NULL,
  `quantity` DOUBLE NULL DEFAULT NULL,
  `amount` DOUBLE NULL DEFAULT NULL,
  `salesorders_sonumber` INT NOT NULL,
  PRIMARY KEY (`linenumber`),
  CONSTRAINT `fk_saleslines_salesorders1`
    FOREIGN KEY (`salesorders_sonumber`)
    REFERENCES `salesorders` (`sonumber`))
ENGINE = InnoDB
AUTO_INCREMENT = 159622
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_saleslines_salesorders1_idx` ON `saleslines` (`salesorders_sonumber` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `salesorders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `salesorders` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `salesorders` (
  `sonumber` INT NOT NULL AUTO_INCREMENT,
  `SalesDate` DATE NULL DEFAULT NULL,
  `DueDate` DATE NULL DEFAULT NULL,
  `DeliveryDate` DATE NULL DEFAULT NULL,
  `IsReturend` TINYINT NULL DEFAULT '0',
  `SoStatus` VARCHAR(1) NULL DEFAULT '1',
  `ContactName` VARCHAR(45) NULL DEFAULT NULL,
  `ContactNo` VARCHAR(45) NULL DEFAULT NULL,
  `isPayed` TINYINT NULL DEFAULT '0',
  `EmpNo` VARCHAR(45) NOT NULL,
  `Total` DOUBLE NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `returndate` DATE NULL DEFAULT NULL,
  `Commission` DOUBLE NULL DEFAULT NULL,
  `ItemQty` DOUBLE NULL DEFAULT NULL,
  `City` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`sonumber`))
ENGINE = InnoDB
AUTO_INCREMENT = 159947
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `uploadlog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uploadlog` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `uploadlog` (
  `upload_id` INT NOT NULL AUTO_INCREMENT,
  `uploadtype` INT NOT NULL,
  `uploadfile` JSON NOT NULL,
  `uploadtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `uploadresult` INT NULL DEFAULT '1',
  PRIMARY KEY (`upload_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 74
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `userlogin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `userlogin` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `userlogin` (
  `UserName` VARCHAR(100) NOT NULL,
  `Employees_idEmployees` INT NULL DEFAULT NULL,
  `Password` VARCHAR(45) NULL DEFAULT NULL,
  `LoginType` TINYINT NOT NULL DEFAULT '0',
  `LastLoginDate` DATE NULL DEFAULT NULL,
  `UserStatus` INT NULL DEFAULT '1',
  PRIMARY KEY (`UserName`),
  CONSTRAINT `fk_UserLogin_Employees1`
    FOREIGN KEY (`Employees_idEmployees`)
    REFERENCES `employees` (`idEmployees`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Employees_idEmployees_UNIQUE` ON `userlogin` (`Employees_idEmployees` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_UserLogin_Employees1_idx` ON `userlogin` (`Employees_idEmployees` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usernotifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usernotifications` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usernotifications` (
  `Employees_idEmployees` INT NULL DEFAULT NULL,
  `PhoneNumber` VARCHAR(45) NULL DEFAULT NULL,
  `IsSMS` TINYINT NULL DEFAULT NULL,
  `IsWeb` TINYINT NULL DEFAULT NULL,
  `Notification` VARCHAR(160) NULL DEFAULT NULL,
  `NotificationTitle` VARCHAR(45) NULL DEFAULT NULL,
  `SentTime` DATETIME NULL DEFAULT NULL,
  `isViewed` TINYINT NULL DEFAULT '0',
  `notificationid` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`notificationid`),
  CONSTRAINT `fk_UserNotifications_Employees1`
    FOREIGN KEY (`Employees_idEmployees`)
    REFERENCES `employees` (`idEmployees`))
ENGINE = InnoDB
AUTO_INCREMENT = 4115
DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;
CREATE INDEX `fk_UserNotifications_Employees1_idx` ON `usernotifications` (`Employees_idEmployees` ASC) VISIBLE;

SHOW WARNINGS;
USE `db_mlm` ;

-- -----------------------------------------------------
-- View `commisiondetailsreport`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `commisiondetailsreport` ;
SHOW WARNINGS;
USE `db_mlm`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`remote`@`%` SQL SECURITY DEFINER VIEW `commisiondetailsreport` AS select `ed`.`idEarning` AS `idEarning`,`ed`.`Price` AS `Price`,`ed`.`Value` AS `Value`,`ed`.`IsDirectCommission` AS `IsDirectCommission`,`ed`.`Employee` AS `Employee`,`s`.`sonumber` AS `SalesOrders_idSalesOrders`,`s`.`ItemQty` AS `SalesQty`,`s`.`Total` AS `SalesValue`,`s`.`DeliveryDate` AS `DeliveryDate` from (`earning_details` `ed` left join `salesorders` `s` on((`ed`.`SalesOrders_idSalesOrders` = `s`.`sonumber`)));
SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;